openapi: 3.0.0
info:
  title: Chuck Norris Facts API
  description: API for Chuck Norris facts
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Development server

paths:
  /:
    get:
      summary: Welcome message
      responses:
        '200':
          description: Welcome message
          content:
            text/plain:
              schema:
                type: string
              example: ¡Bienvenido al servidor de facts!

  /facts:
    get:
      summary: Get all Chuck Norris facts
      responses:
        '200':
          description: A list of Chuck Norris facts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    fact:
                      type: string
                      example: Chuck Norris can divide by zero.
                    timestamp:
                      type: string
                      format: date-time
                      example: "2024-06-29T12:00:00Z"
    post:
      summary: Add a new Chuck Norris fact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: Chuck Norris can slam a revolving door.
      responses:
        '201':
          description: ID of the inserted Chuck Norris fact
          content:
            application/json:
              schema:
                type: object
                properties:
                  inserted_id:
                    type: integer
                    example: 2

  /facts/random:
    get:
      summary: Get a random Chuck Norris fact
      responses:
        '200':
          description: A random Chuck Norris fact
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 4
                  fact:
                    type: string
                    example: Chuck Norris can unscramble an egg.
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-06-29T16:00:00Z"

  /facts/{fact_id}:
    get:
      summary: Get a Chuck Norris fact by ID
      parameters:
        - name: fact_id
          in: path
          required: true
          schema:
            type: integer
          example: 3
      responses:
        '200':
          description: A Chuck Norris fact
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 3
                  fact:
                    type: string
                    example: Chuck Norris can slam a revolving door.
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-06-29T14:00:00Z"
        '404':
          description: Fact not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Fact not found

  /facts/date/{date}:
    get:
      summary: Get Chuck Norris facts by date
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
          example: "2024-06-29"
      responses:
        '200':
          description: Chuck Norris facts on the specified date
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 6
                    text:
                      type: string
                      example: When Chuck Norris goes to donate blood he declines the syringe and instead requests a hand gun and a bucket.
                    timestamp:
                      type: string
                      format: date-time
                      example: "2024-06-29T18:49:43.283835Z"
        '400':
          description: Invalid date format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid date format. Use YYYY-MM-DD
